# Generated by Django 2.1.1 on 2019-02-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('phone_num', models.TextField()),
                ('Category', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('comment', models.TextField()),
                ('rating', models.FloatField()),
                ('restau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webReview.Restaurant')),
            ],
        ),
    ]
